### ISSUE TITLE
Tau adaptive takes unreasonably long to run

### ISSUE THREAD

**Issue by dileep-kishore** [Heuro-labs/pyssa#103]

**Comment by dileep-kishore** [comment]
Possible reasons

1. `cache` is set to `False`
2. `numba` problem
3. Implementation/algorithm issues

**Comment by sriki18** [comment]
1. Consider using Intel SVML (http://numba.pydata.org/numba-doc/dev/user/performance-tips.html) although end user may not be expected to actually get this for speed.
2. Add signatures to the function decorators.
3.
