### ISSUE TITLE
Roulette taking 45% time!

### ISSUE THREAD

**Issue by sriki18** [Heuro-labs/pyssa#107]
Profiling suggests that of a run of 2s, the line that calls roulette takes 45% of time or around 1s. But the total time indicated just above the roulette function says it is only 0.2s. So likely there is some time being spent in parsing the returned data, which is much higher than the time taken to run roulette.

**Comment by sriki18** [comment]
One thing we could try is instead of working with Tuples, use memory views.

**Comment by dileep-kishore** [comment]
Lowered to ~7-10 % of time now
