### ISSUE TITLE
Add accuracy tests from the sbml-test-suite

### ISSUE THREAD

**Issue by dileep-kishore** [Heuro-labs/pyssa#87]

**Comment by dileep-kishore** [comment]
https://github.com/sbmlteam/sbml-test-suite/tree/master/cases/stochastic

**Comment by dileep-kishore** [comment]
|Test number|Reason|
|:---------:|:----:|
|00002|No local|

**Comment by sriki18** [comment]
00039 is failing because of exiting too early
