### ISSUE TITLE
Algorithm benchmarks

### ISSUE THREAD

**Issue by dileep-kishore** [Heuro-labs/pyssa#98]
1. Use examples from https://link.springer.com/article/10.1007/s11538-018-0464-9
2. ~~Use `tellurium` and `GillesPy` as standards to compare with~~
3. `BioSimulator.jl` and `Gillespie.jl`
4. `GillespieSSA` an R package

**Comment by sriki18** [comment]
https://cran.r-project.org/web/packages/GillespieSSA/index.html << R package that may be useful to compare with
